trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'GitPush'
  jobs:
    - job: GitPush
      steps:
        - checkout: self
          persistCredentials: true
        - script: |
            git config --global user.email "zerods5830@gmail.com"
            git config --global user.name "Richard6536"
            git init
            git add .
            git commit -m "another commit"
            git remote set-url origin https://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@github.com/Richard6536/test.git
            git pull --rebase origin HEAD:refs/heads/main
            git push -f origin HEAD:refs/heads/main
          displayName: 'Git push to remote repository'
